/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/sysinit.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/DrillSim3.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/DrillSim3.or
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/system.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/lnfodwrf.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/exeinfo.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/strings.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/fpintres.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/objpas.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/cthreads.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/interfaces.o
/Applications/Lazarus/lcl/units/x86_64-darwin/forms.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tachartlazaruspkg.o
/Applications/Lazarus/components/lazcontrols/lib/x86_64-darwin/cocoa/lazcontrols.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/DrillSimGUI.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/FormGeneralData.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/FormHoleData.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/FormConfigDefaults.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/FormPipeData.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/FormBitData.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/FormPumpData.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/FormSurfaceEquipmentData.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/FormWellTestData.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/FormGeologyData.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/FormMudData.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/FormDisplayWellData.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/FormUnitsOfMeasure.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/uversion.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/baseunix.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/unix.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/unixtype.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/initc.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/sysctl.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/unixutil.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/ctypes.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/cwstring.o
/Applications/Lazarus/lcl/units/x86_64-darwin/interfacebase.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/dynlibs.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/unixcp.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/dl.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/types.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/classes.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/sysutils.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/math.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fpimage.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/lazutf8.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/integerlist.o
/Applications/Lazarus/lcl/units/x86_64-darwin/lcltype.o
/Applications/Lazarus/lcl/units/x86_64-darwin/lclproc.o
/Applications/Lazarus/lcl/units/x86_64-darwin/lmessages.o
/Applications/Lazarus/lcl/units/x86_64-darwin/lclplatformdef.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/graphtype.o
/Applications/Lazarus/lcl/units/x86_64-darwin/graphmath.o
/Applications/Lazarus/lcl/units/x86_64-darwin/intfgraphics.o
/Applications/Lazarus/lcl/units/x86_64-darwin/themes.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/errors.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/sysconst.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/typinfo.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/rtlconsts.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/fpcadds.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl-objpas/strutils.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-base/gettext.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/univint/MacOSAll.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/macpas.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/blockrtl.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/univint/MacTypes.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/univint/CoreAudioTypes.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/fgl.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/laz_avl_tree.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/lazfileutils.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/lazutilities.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/lazmethodlist.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/lazutf8classes.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/lazloggerbase.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/laztracer.o
/Applications/Lazarus/lcl/units/x86_64-darwin/lclstrconsts.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/lazutilsstrconsts.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/lazclasses.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fpreadbmp.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fpwritebmp.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/bmpcomn.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fpreadpng.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fpwritepng.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fpreadtiff.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fpwritetiff.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fptiffcmn.o
/Applications/Lazarus/lcl/units/x86_64-darwin/lclversion.o
/Applications/Lazarus/lcl/units/x86_64-darwin/icnstypes.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fpimgcmn.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/pngcomn.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/paszlib/zstream.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/paszlib/zbase.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/paszlib/gzio.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/hash/crc.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/paszlib/zdeflate.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/paszlib/zinflate.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/paszlib/trees.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/paszlib/adler.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/paszlib/infblock.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/paszlib/infutil.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/paszlib/infcodes.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/paszlib/inftrees.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/paszlib/inffast.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/lazversion.o
/Applications/Lazarus/lcl/units/x86_64-darwin/graphics.o
/Applications/Lazarus/lcl/units/x86_64-darwin/lclintf.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-base/contnrs.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fpcanvas.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fpreadpnm.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fpwritepnm.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fpreadjpeg.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fpwritejpeg.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fpreadgif.o
/Applications/Lazarus/lcl/units/x86_64-darwin/lresources.o
/Applications/Lazarus/lcl/units/x86_64-darwin/lclrescache.o
/Applications/Lazarus/lcl/units/x86_64-darwin/wsreferences.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/clipping.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jpeglib.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jdapimin.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jdatasrc.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jdapistd.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jmorecfg.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jdeferr.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jinclude.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jerror.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jmemmgr.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jdmarker.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jdinput.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jcomapi.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jutils.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jmemnobs.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jdmaster.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jdcolor.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jdsample.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jdpostct.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jddctmgr.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jdphuff.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jdhuff.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jdcoefct.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jdmainct.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jquant1.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jquant2.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jdmerge.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jdct.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jidctfst.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jidctint.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jidctflt.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jidctred.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jcapistd.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jcapimin.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jdatadst.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jcparam.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jcinit.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jcmarker.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jcphuff.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jchuff.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jcmaster.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jccolor.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jcsample.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jcprepct.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jcdctmgr.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jccoefct.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jcmainct.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jfdctint.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jfdctfst.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/pasjpeg/jfdctflt.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl-objpas/variants.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/lazconfigstorage.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/dynqueue.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl-objpas/varutils.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/avglvltree.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/lazdbglog.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-base/syncobjs.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/objc.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/objcbase.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/cocoaint/CocoaAll.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/fileutil.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/utf8process.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/lazsysutils.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/maps.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/cocoaint/DefinedClassesFoundation.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/cocoaint/DefinedClassesCoreImage.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/cocoaint/DefinedClassesQuartzCore.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/cocoaint/DefinedClassesCoreData.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/cocoaint/DefinedClassesAppKit.o
/Applications/Lazarus/lcl/units/x86_64-darwin/tmschema.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/masks.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-process/process.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-process/pipes.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/termio.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoaint.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoaprivate.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoautils.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoagdiobjects.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoa_extra.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoawsmenus.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoawsforms.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoawindows.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoascrollers.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoawsclipboard.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoatextedits.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoawscommon.o
/Applications/Lazarus/lcl/units/x86_64-darwin/lclmessageglue.o
/Applications/Lazarus/lcl/units/x86_64-darwin/controls.o
/Applications/Lazarus/lcl/units/x86_64-darwin/menus.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoawsfactory.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/univint/CGGeometry.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/univint/CFBase.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/univint/CFDictionary.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/univint/CGBase.o
/Applications/Lazarus/lcl/units/x86_64-darwin/lclclasses.o
/Applications/Lazarus/lcl/units/x86_64-darwin/wslclclasses.o
/Applications/Lazarus/lcl/units/x86_64-darwin/customdrawndrawers.o
/Applications/Lazarus/lcl/units/x86_64-darwin/customdrawn_mac.o
/Applications/Lazarus/lcl/units/x86_64-darwin/imglist.o
/Applications/Lazarus/lcl/units/x86_64-darwin/propertystorage.o
/Applications/Lazarus/lcl/units/x86_64-darwin/actnlist.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/uitypes.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fpimgcanv.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fppixlcanv.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/pixtools.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/ellipses.o
/Applications/Lazarus/lcl/units/x86_64-darwin/wsimglist.o
/Applications/Lazarus/lcl/units/x86_64-darwin/wsproc.o
/Applications/Lazarus/lcl/units/x86_64-darwin/wsfactory.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-base/rttiutils.o
/Applications/Lazarus/lcl/units/x86_64-darwin/wsmenus.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/lazlogger.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/lazstringutils.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-base/custapp.o
/Applications/Lazarus/lcl/units/x86_64-darwin/customtimer.o
/Applications/Lazarus/lcl/units/x86_64-darwin/clipbrd.o
/Applications/Lazarus/lcl/units/x86_64-darwin/helpintfs.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-base/singleinstance.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/chm/fasthtmlparser.o
/Applications/Lazarus/lcl/units/x86_64-darwin/wscontrols.o
/Applications/Lazarus/lcl/units/x86_64-darwin/wsforms.o
/Applications/Lazarus/lcl/units/x86_64-darwin/comctrls.o
/Applications/Lazarus/lcl/units/x86_64-darwin/extctrls.o
/Applications/Lazarus/lcl/units/x86_64-darwin/stdctrls.o
/Applications/Lazarus/lcl/units/x86_64-darwin/toolwin.o
/Applications/Lazarus/lcl/units/x86_64-darwin/buttons.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/textstrings.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/extendedstrings.o
/Applications/Lazarus/lcl/units/x86_64-darwin/wsstdctrls.o
/Applications/Lazarus/lcl/units/x86_64-darwin/popupnotifier.o
/Applications/Lazarus/lcl/units/x86_64-darwin/wsextctrls.o
/Applications/Lazarus/lcl/units/x86_64-darwin/imagelistcache.o
/Applications/Lazarus/lcl/units/x86_64-darwin/wsbuttons.o
/Applications/Lazarus/lcl/units/x86_64-darwin/wscomctrls.o
/Applications/Lazarus/lcl/units/x86_64-darwin/wstoolwin.o
/Applications/Lazarus/lcl/units/x86_64-darwin/customdrawn_common.o
/Applications/Lazarus/lcl/units/x86_64-darwin/messages.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoacaret.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoawsstdctrls.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoabuttons.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoatables.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoathemes.o
/Applications/Lazarus/lcl/units/x86_64-darwin/spin.o
/Applications/Lazarus/lcl/units/x86_64-darwin/pairsplitter.o
/Applications/Lazarus/lcl/units/x86_64-darwin/dialogs.o
/Applications/Lazarus/lcl/units/x86_64-darwin/checklst.o
/Applications/Lazarus/lcl/units/x86_64-darwin/calendar.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoawsbuttons.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoawsextctrls.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoawscomctrls.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoawsdialogs.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoawsspin.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoawschecklst.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoawsdatepicker.o
/Applications/Lazarus/lcl/units/x86_64-darwin/wsspin.o
/Applications/Lazarus/lcl/units/x86_64-darwin/wspairsplitter.o
/Applications/Lazarus/lcl/units/x86_64-darwin/buttonpanel.o
/Applications/Lazarus/lcl/units/x86_64-darwin/lcltaskdialog.o
/Applications/Lazarus/lcl/units/x86_64-darwin/wsdialogs.o
/Applications/Lazarus/lcl/units/x86_64-darwin/wschecklst.o
/Applications/Lazarus/lcl/units/x86_64-darwin/wscalendar.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoatabcontrols.o
/Applications/Lazarus/lcl/units/x86_64-darwin/cocoa/cocoadatepicker.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tagraph.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tachartaxis.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tachartutils.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tacustomseries.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tasources.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tadbsource.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/taseries.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/taserieseditor.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tasubcomponentseditor.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tatools.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tatransformations.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tatypes.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tadrawutils.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tamultiseries.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/talegend.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tastyles.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tafuncseries.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/talegendpanel.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/taradialseries.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tacustomsource.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tageometry.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tanavigation.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tadrawercanvas.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tadrawersvg.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/taintervalsources.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tachartaxisutils.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tachartlistbox.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/taenumerators.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tadatapointseditor.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tachartextentlink.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tatooleditors.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tamath.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tachartimagelist.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tachartteechart.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tadatatools.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/taanimatedsource.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tatextelements.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/taaxissource.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/taseriespropeditors.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tacustomfuncseries.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tafitutils.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/taguiconnector.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tadiagram.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tadiagramdrawing.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tadiagramlayout.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tachartstrconsts.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tachartcombos.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tahtml.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tafonts.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/taexpressionseries.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/taopengl.o
/Applications/Lazarus/components/tachart/lib/x86_64-darwin/cocoa/tafitlib.o
/Applications/Lazarus/packager/units/x86_64-darwin/lazaruspackageintf.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/numlib/spe.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/numlib/typ.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/numlib/roo.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/chm/htmlutil.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-xml/htmldefs.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl-objpas/dateutils.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/componenteditors.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/propedits.o
/Applications/Lazarus/lcl/units/x86_64-darwin/grids.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/lazstringgridedit.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/checklistboxeditordlg.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/checkgroupeditordlg.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/propeditutils.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/componentreg.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/objinspstrconsts.o
/Applications/Lazarus/lcl/units/x86_64-darwin/maskedit.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/dynamicarray.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/laz2_xmlcfg.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/lcsvutils.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/lazfilecache.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/laz2_dom.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/laz2_xmlread.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/laz2_xmlwrite.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/laz2_xmlutils.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-base/uriparser.o
/Applications/Lazarus/lcl/units/x86_64-darwin/wsgrids.o
/Applications/Lazarus/lcl/units/x86_64-darwin/arrow.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/idewindowintf.o
/Applications/Lazarus/lcl/units/x86_64-darwin/industrialbase.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/ideoptionsintf.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/lazideintf.o
/Applications/Lazarus/lcl/units/x86_64-darwin/lazhelphtml.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/baseideintf.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/ideopteditorintf.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/compoptsintf.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/projectintf.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/ideexterntoolintf.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/srceditorintf.o
/Applications/Lazarus/lcl/units/x86_64-darwin/lazhelpintf.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/macrointf.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/macrodefintf.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/editorsyntaxhighlighterdef.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/newitemintf.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/projpackintf.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/idecommands.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/ideimagesintf.o
/Applications/Lazarus/lcl/units/x86_64-darwin/editbtn.o
/Applications/Lazarus/lcl/units/x86_64-darwin/valedit.o
/Applications/Lazarus/lcl/units/x86_64-darwin/filectrl.o
/Applications/Lazarus/components/lazcontrols/lib/x86_64-darwin/cocoa/checkboxthemed.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/stringhashlist.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/packagedependencyintf.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/frmselectprops.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/stringspropeditdlg.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/keyvalpropeditdlg.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/collectionpropeditform.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/filefilterpropeditor.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/pagespropeditdlg.o
/Applications/Lazarus/lcl/units/x86_64-darwin/extdlgs.o
/Applications/Lazarus/lcl/units/x86_64-darwin/groupededit.o
/Applications/Lazarus/lcl/units/x86_64-darwin/calendarpopup.o
/Applications/Lazarus/lcl/units/x86_64-darwin/timepopup.o
/Applications/Lazarus/lcl/units/x86_64-darwin/calcform.o
/Applications/Lazarus/lcl/units/x86_64-darwin/wsextdlgs.o
/Applications/Lazarus/lcl/units/x86_64-darwin/shellctrls.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/texttools.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/idedialogs.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/lazmsgdialogs.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-db/db.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl-objpas/fmtbcd.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-base/maskutils.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-db/dbconst.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/numlib/sle.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/numlib/inv.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/numlib/omv.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/numlib/dsl.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/numlib/mdt.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/numlib/ipf.o
/Applications/Lazarus/lcl/units/x86_64-darwin/graphutil.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/easylazfreetype.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/lazfreetype.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/ttraster.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/tttypes.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/tterror.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/ttcalc.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/ttmemory.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/tttables.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/ttcache.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/ttfile.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/ttcmap.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/ttobjs.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/ttload.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/ttgload.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/ttinterp.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/ttprofile.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/lazfreetypefontcollection.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-base/base64.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-base/fpexprpars.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/opengl/gl.o
/Applications/Lazarus/components/lazutils/lib/x86_64-darwin/lazfreetypefpimagedrawer.o
/Applications/Lazarus/components/lazcontrols/lib/x86_64-darwin/cocoa/dividerbevel.o
/Applications/Lazarus/components/lazcontrols/lib/x86_64-darwin/cocoa/extendednotebook.o
/Applications/Lazarus/components/lazcontrols/lib/x86_64-darwin/cocoa/listfilteredit.o
/Applications/Lazarus/components/lazcontrols/lib/x86_64-darwin/cocoa/listviewfilteredit.o
/Applications/Lazarus/components/lazcontrols/lib/x86_64-darwin/cocoa/treefilteredit.o
/Applications/Lazarus/components/lazcontrols/lib/x86_64-darwin/cocoa/shortpathedit.o
/Applications/Lazarus/components/lazcontrols/lib/x86_64-darwin/cocoa/lvlgraphctrl.o
/Applications/Lazarus/components/lazcontrols/lib/x86_64-darwin/cocoa/extendedtabcontrols.o
/Applications/Lazarus/components/lazcontrols/lib/x86_64-darwin/cocoa/spinex.o
/Applications/Lazarus/components/lazcontrols/lib/x86_64-darwin/cocoa/smallorderedseteditor.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl-console/crt.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgracontrols-master/lib/x86_64-darwin-cocoa-3.2.0/bcbutton.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgracontrols-master/lib/x86_64-darwin-cocoa-3.2.0/bclistbox.o
/Users/simonambridge/Documents/MyProjects/Drillsim3/synapse40/source/lib/lib/x86_64-darwin/blcksock.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/usplashabout.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/DrillSimVariables.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/DrillSimStartup.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/DrillSimFile.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/DrillSimDataResets.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/DrillSimUtilities.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/DrillSimHoleChecks.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/DrillSimMessageToMemo.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/SimulateCommandProcessor.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/SimulateUpdate.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/SimulateRAMs.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/SimulateHoleCalcs.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/SimulateHydraulicCalcs.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/SimulateDrillingCalcs.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/SimulateKick.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrabitmap.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrabitmaptypes.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgracontrols-master/lib/x86_64-darwin-cocoa-3.2.0/bcthememanager.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgracontrols-master/lib/x86_64-darwin-cocoa-3.2.0/bctypes.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgracontrols-master/lib/x86_64-darwin-cocoa-3.2.0/bcbasectrls.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-json/fpjsonrtti.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-json/fpjson.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgraclasses.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgramacbitmap.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgragraphics.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgraunicode.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgramultifiletype.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrautf8.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fpreadxwd.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fpreadxpm.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fpwritepcx.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fpwritetga.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fpwritexpm.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/xwdfile.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/pcxcomn.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/targacmn.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgralclbitmap.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgradefaultbitmap.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgracanvas.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgracanvas2d.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgratransform.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgratextbidi.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/universaldrawer.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgragrayscalemask.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrapen.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrapath.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrapolygon.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrapolygonaliased.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrablend.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgraresample.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrafillinfo.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgragradientscanner.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrasse.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgraarrow.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrareadbmp.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrareadjpeg.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrawritepng.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrawritetiff.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrafilterblur.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrafiltertype.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgraunicodetext.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrafilters.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fpreadpcx.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgradithering.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrafilterscanner.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrapalette.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-base/avl_tree.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-base/bufstream.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgratext.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrareadbmpmiomap.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrareadgif.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrareadico.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrareadlzp.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrareadpcx.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrareadpng.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrareadpsd.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrareadtga.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrareadxpm.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrawritelzp.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrareadwebp.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgrawritewebp.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgralzpcommon.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgracompressablebitmap.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fpreadpsd.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-image/fpreadtga.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/libwebp.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-json/jsonparser.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-json/jsonscanner.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-json/jsonreader.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/graphpropedits.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgracontrols-master/lib/x86_64-darwin-cocoa-3.2.0/bctools.o
/Applications/Lazarus/components/ideintf/units/x86_64-darwin/cocoa/graphicpropedit.o
/Applications/Lazarus/lcl/units/x86_64-darwin/stdactns.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgracontrols-master/lib/x86_64-darwin-cocoa-3.2.0/bgravirtualscreen.o
/Users/simonambridge/.lazarus/onlinepackagemanager/packages/bgrabitmap-master/bgrabitmap/lib/x86_64-darwin-cocoa-3.2.0/bgraslicescaling.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-base/inifiles.o
/Users/simonambridge/Documents/MyProjects/Drillsim3/synapse40/source/lib/lib/x86_64-darwin/synafpc.o
/Users/simonambridge/Documents/MyProjects/Drillsim3/synapse40/source/lib/lib/x86_64-darwin/synsock.o
/Users/simonambridge/Documents/MyProjects/Drillsim3/synapse40/source/lib/lib/x86_64-darwin/synautil.o
/Users/simonambridge/Documents/MyProjects/Drillsim3/synapse40/source/lib/lib/x86_64-darwin/synacode.o
/Users/simonambridge/Documents/MyProjects/Drillsim3/synapse40/source/lib/lib/x86_64-darwin/synaip.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl-extra/sockets.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-net/netdb.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-res/resource.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-res/versiontypes.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-res/versionresource.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-res/resdatastream.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-res/resourcetree.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-res/resmerger.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-res/resfactory.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-res/stringtableresource.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-res/groupiconresource.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-res/groupcursorresource.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-res/groupresource.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/fcl-res/icocurtypes.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/DrillSimUnitsOfMeasure.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/SimulateVolumes.o
/usr/local/Cellar/fpc/3.2.0/lib/fpc/3.2.0/units/x86_64-darwin/rtl/dos.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/DrillSimMath.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/SimulateHydrostaticCalcs.o
/Users/simonambridge/Documents/MyProjects/DrillSim3/lib/x86_64-darwin/SimulateRheology.o
